### ISSUE TITLE
V42.T-1 Deploy on AWS and test  <VMC 42>

### ISSUE THREAD

**Issue by joeyzoland** [Sree-Makam/POTR#22]
This is a preliminary step, simply so that the developers can test the code online before we get the client to set up his/her AWS account.

**Comment by chosenman** [comment]
October 29
Trying to deploy our project on ubuntu server (the same as AWS): 
http://yarik-deploy.com/potr/
Now fighting issue "Invalid Host header" while running

**Comment by blai00** [comment]
test

**Comment by chosenman** [comment]
Slack doesn't work, so a little report here. We found with Jonathan a couple bugs, while deployment (http://yarik-deploy.com/ - is url where it is now deployed. And also there is a link to AWS server... I don't have it right now ):
1. After login doesn't work url( http://yarik-deploy.com/package ) as a GET request. It is line 34 (this file https://github.com/Sree-Makam/POTR/blob/master/client/src/LoginReg/loginForm.js ) 
This is general problem after deployment for all "window.location.href" usage. So far trying to identify how better to solve this, there are a several approaches. 
2. Doesn't work on Firefox (at least on my Mac Book)

**Comment by jsalinlee** [comment]
AWS address: http://34.216.5.14/
